spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nicefish?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 10000
    validationQuery: select 1
    
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update

  jackson: 
    serialization:
      indent_output: true